### ISSUE TITLE
Program does not download playlists into separate subdirectories

### ISSUE THREAD

**Issue by QueasyQolon** [shaked6540/YoutubePlaylistDownloader#67]
The application no longer places playlists into individual directories. YouTube may have changed their libraries again.

**Comment by shaked6540** [comment]
I just tested it and it works just fine. Make sure you check the "Save every playlist in a different folder" checkbox in the settings like this: 
![image](https://user-images.githubusercontent.com/13851815/151054227-665f5ef6-a115-4bcf-95b5-2cae8d751b4c.png)

**Comment by QueasyQolon** [comment]
[1/25/2022 6:36:22 AM], [Dispatcher.InvokeAsync at DownloadPage.xaml.cs StartDownloading]:

System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at YoutubePlaylistDownloader.DownloadPage.<>c__DisplayClass62_4.<StartDownloading>b__12()
   
   That's the error message.

**Comment by shaked6540** [comment]
Is that the entire content of the file? It doesn't tell me much, looks like it just failed to calculate the average download speed which shouldn't affect anything except the download speed indicator. 

Could you tell me what settings you were using, what playlists or videos you were trying to download, and what did you do to cause this error?

**Comment by QueasyQolon** [comment]
[1/25/2022 4:55:11 AM], [LoadConsts at GlobalConsts]:

Config file does not exist, restoring defaults


[1/25/2022 4:55:11 AM], [RestoreDefaults at GlobalConsts]:

Restoring defaults


[1/25/2022 5:40:11 AM], [Dispatcher.InvokeAsync at DownloadPage.xaml.cs StartDownloading]:

System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at YoutubePlaylistDownloader.DownloadPage.<>c__DisplayClass62_4.<StartDownloading>b__12()


[1/25/2022 6:24:59 AM], [Dispatcher.InvokeAsync at DownloadPage.xaml.cs StartDownloading]:

System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at YoutubePlaylistDownloader.DownloadPage.<>c__DisplayClass62_4.<StartDownloading>b__12()


[1/25/2022 6:32:10 AM], [Dispatcher.InvokeAsync at DownloadPage.xaml.cs StartDownloading]:

System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at YoutubePlaylistDownloader.DownloadPage.<>c__DisplayClass62_4.<StartDownloading>b__12()


[1/25/2022 6:36:22 AM], [Dispatcher.InvokeAsync at DownloadPage.xaml.cs StartDownloading]:

System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at YoutubePlaylistDownloader.DownloadPage.<>c__DisplayClass62_4.<StartDownloading>b__12()


[1/25/2022 10:03:48 PM], [Dispatcher.InvokeAsync at DownloadPage.xaml.cs StartDownloading]:

System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at YoutubePlaylistDownloader.DownloadPage.<>c__DisplayClass62_4.<StartDownloading>b__12()


[1/25/2022 10:06:32 PM], [Dispatcher.InvokeAsync at DownloadPage.xaml.cs StartDownloading]:

System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at YoutubePlaylistDownloader.DownloadPage.<>c__DisplayClass62_4.<StartDownloading>b__12()

That's the entire error log. 

Also I'm trying to download Karl Smallwood's YouTube channel (https://www.youtube.com/channel/UCaR-e8ComPih10DqPi3sdWg) but whenever it starts the download it just downloads all the videos and does not actually create any subdirectories. I tried waiting until the downloads finished, but no dice there either. 

The only settings that I have checked are "place playlists into separate folders" and "prefer videos with a resolution of 720p". Is there something I'm missing? Is the program expecting a specific page of the channel? Also I excluded my antivirus from affecting the program and nothing changed there either.

**Comment by shaked6540** [comment]
Thanks for letting me know about this bug! I released a new version which should fix it. Let me know if it works

**Comment by QueasyQolon** [comment]
The program now downloads the individual channels into separate folders, but it does not save the individual playlists on the channel into their own folders.

**Comment by shaked6540** [comment]
The program was never meant to do that, when inserting a link to a channel the expected result is for all the videos in the channel to download.

**Comment by QueasyQolon** [comment]
..oh. Well that explains things. My bad.

**Comment by shaked6540** [comment]
No worries, there was still a bug that was fixed after all :)
